{{- if and ( .Values.server.enabled ) ( .Values.server.ingress.enabled ) -}}
{{- $serviceName := include "chart.server.fullname" . }}
---
apiVersion: {{ template "chart.server.ingress.apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.server.ingress.annotations }}
  annotations:
{{ toYaml .Values.server.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "chart.server.labels" . | nindent 4 }}
  name: {{ template "chart.server.fullname" . }}
{{ include "chart.namespace" . | indent 2 }}
spec:
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
  rules:
  {{- range .Values.server.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
{{ if $.Values.server.ingress.extraPaths }}
{{ toYaml $.Values.server.ingress.extraPaths | indent 10 }}
{{- end }}
          - path: {{ $.Values.server.ingress.path }}
            pathType: {{ $.Values.server.ingress.pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
          - path: {{ $.Values.server.ingress.path }}
            pathType: {{ $.Values.server.ingress.pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 443
{{- end -}}
{{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end }}
{{- end -}}
