{{- if and ( .Values.server.enabled ) ( .Values.server.greeter.configFromSecret ) -}}
---
apiVersion: {{ template "chart.server.secret.apiVersion" . }}
kind: "Secret"
metadata:
  name: "{{ template "chart.server.fullname" . }}"
{{- if .Values.server.secretAnnotations }}
  annotations:
    {{ toYaml .Values.server.secretAnnotations | nindent 4 }}
{{- end }}
  labels:
  {{- include "chart.server.labels" . | nindent 4 }}
{{ include "chart.namespace" . | indent 2 }}
data:
    {{- include "chart.server.greeter.env_" . | indent 4 }}
{{- end -}}
